octopus:
  environments:
    - development
    - test
  development:
    moodshard:
      adapter: sqlite3
      database: db/mood_shard
    commentshard:
      adapter: sqlite3
      database: db/comment_shard